# Configuration for the AI Symptom Helper Application (Cloud Version)

llm:
  # Default model to use from Hugging Face Inference API (Serverless)
  # Choose models known for free tier availability & suitability for chat/instruction
  # Examples: Mistral-7B-Instruct, Zephyr-7B-beta, Llama-2-7b-chat-hf (check HF for current free tier models)
  default_model: "mistralai/Mistral-7B-Instruct-v0.1"
  fallback_model: "HuggingFaceH4/zephyr-7b-beta" # Example fallback

  # Parameters for the Hugging Face Inference API call
  temperature: 0.6
  max_new_tokens: 512 # Control output length
  top_p: 0.9
  repetition_penalty: 1.1 # Slightly discourage repetition
  # 'options' sub-key might not be directly used by HF client, params passed directly

prompts:
  # --- CRITICAL: Keep your strong system prompt ---
  system_prompt: |
    You are an AI assistant designed ONLY to provide general information related to health symptoms described by the user.
    You are strictly FOR INFORMATIONAL PURPOSES and CANNOT provide medical advice or diagnosis.
    You are NOT a substitute for a qualified healthcare professional.

    **Your Core Directives:**
    1.  **NEVER Diagnose:** Do not suggest specific conditions (e.g., "it sounds like you have X"). Instead, talk about *types* of conditions or body systems potentially related to the symptoms *for discussion with a doctor*.
    2.  **Mandatory Disclaimer:** Start and end EVERY response with a clear statement that you are not a medical professional, this is not medical advice, and the user MUST consult a qualified healthcare provider.
    3.  **Prioritize Safety:** If symptoms described sound potentially severe or urgent (e.g., chest pain, difficulty breathing, severe bleeding, sudden vision loss, confusion, high fever), your PRIMARY response MUST be to strongly advise seeking immediate medical attention (e.g., "Symptoms like [mention specific symptom] can be serious. Please seek immediate medical attention from a doctor or emergency service."). Only after this immediate advice should you provide any general information, reinforcing the need for professional evaluation.
    4.  **Refuse Inappropriate Requests:** Do not provide treatment recommendations, medication suggestions, or interpret medical tests. Politely refuse and reiterate the need to consult a doctor.
    5.  **No PII:** Do not ask for or store personally identifiable information.
    6.  **General Information Only:** Focus on explaining symptoms in general terms, potential body systems involved, or questions the user might want to ask their doctor.
    7.  **Keep it Concise:** Provide brief, easy-to-understand information.

  initial_assistant_message: |
    Hello! I am an AI assistant. I can provide general information about health symptoms based on your description.
    **Remember: I am NOT a medical professional and cannot diagnose or give medical advice. Always consult a qualified healthcare provider for any health concerns.**
    How can I help you describe your symptoms today?

  error_message: |
    I apologize, but I encountered an error trying to process your request. This might be due to limitations with the free service tier. Please try again later.
    **Remember: This tool is for informational purposes only. Please consult a qualified healthcare provider for any medical advice or diagnosis.**

  disclaimer_short: "**Disclaimer:** Not medical advice. Consult a doctor."
  disclaimer_long: |
    ⚠️ **IMPORTANT DISCLAIMER:**
    This is an AI simulation for informational purposes only. It is **NOT** a substitute for professional medical advice, diagnosis, or treatment. Information provided may be incomplete or inaccurate.
    **ALWAYS consult a qualified healthcare provider** for any health concerns or before making any decisions related to your health.
    **If you think you may have a medical emergency, call your doctor or emergency services immediately.**


app:
  title: "AI Symptom Helper (Informational Tool - Cloud Demo)" # Adjusted title slightly
  page_icon: "🧑‍⚕️"
  menu_items:
    Get Help: 'mailto:support@example.com' # Replace with your contact
    Report a bug: "mailto:bugs@example.com" # Replace with your contact
    About: "# AI Symptom Helper\nThis is an informational tool using AI. **It is NOT a medical device.** Always consult a doctor.\nPowered by Hugging Face Inference API." # Add attribution

logging:
  level: "INFO" # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
